### ISSUE TITLE
Character info from index 2 is not valid JSON! SyntaxError: JSON5: invalid character 'U' at 1:2

### ISSUE THREAD

**Issue by skvili** [TavernAI/TavernAI-v1#127]
What am I doing wrong? Installed according to the instructions, no problem. When I start up, I get errors like this. The new character appears in the list every once in a while.

`./start-linux.sh

up to date, audited 223 packages in 781ms

40 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Launching...
TavernAI started: http://127.0.0.1:8000
Character info from index 2 is not valid JSON! SyntaxError: JSON5: invalid character 'U' at 1:2
    at syntaxError (/home/skvili/Ai/TavernAI/node_modules/json5/lib/parse.js:1110:17)
    at invalidChar (/home/skvili/Ai/TavernAI/node_modules/json5/lib/parse.js:1055:12)
    at Object.value (/home/skvili/Ai/TavernAI/node_modules/json5/lib/parse.js:309:15)
    at lex (/home/skvili/Ai/TavernAI/node_modules/json5/lib/parse.js:100:42)
    at Object.parse (/home/skvili/Ai/TavernAI/node_modules/json5/lib/parse.js:25:17)
    at /home/skvili/Ai/TavernAI/server.js:788:28 {
  lineNumber: 1,
  columnNumber: 2
}
Pre-parsed character data:
[Unicode encoded text]
Character info from index 2 is not valid JSON! SyntaxError: JSON5: invalid character 'U' at 1:2
    at syntaxError (/home/skvili/Ai/TavernAI/node_modules/json5/lib/parse.js:1110:17)
    at invalidChar (/home/skvili/Ai/TavernAI/node_modules/json5/lib/parse.js:1055:12)
    at Object.value (/home/skvili/Ai/TavernAI/node_modules/json5/lib/parse.js:309:15)
    at lex (/home/skvili/Ai/TavernAI/node_modules/json5/lib/parse.js:100:42)
    at Object.parse (/home/skvili/Ai/TavernAI/node_modules/json5/lib/parse.js:25:17)
    at /home/skvili/Ai/TavernAI/server.js:788:28 {
  lineNumber: 1,
  columnNumber: 2
}
Pre-parsed character data:
[Unicode encoded text]
`

**Comment by LeyendaV** [comment]
I'm also having a _SyntaxError: JSON5: invalid character_ error with one of my chars, and I'm being unable to understand what's the actual issue.

**Comment by skvili** [comment]
> I'm also having a _SyntaxError: JSON5: invalid character_ error with one of my chars, and I'm being unable to understand what's the actual issue.

I even tried deleting the contents of the TavernAI/public/characters/ and TavernAI/public/chats/ directories, but I still get this error when the server starts up. At the same time, everything seems to work as it should. Just periodically, a new character doesn't show up in the list of characters. I can't trace the pattern.

**Comment by LeyendaV** [comment]
> > I'm also having a _SyntaxError: JSON5: invalid character_ error with one of my chars, and I'm being unable to understand what's the actual issue.
> 
> I even tried deleting the contents of the TavernAI/public/characters/ and TavernAI/public/chats/ directories, but I still get this error when the server starts up. At the same time, everything seems to work as it should. Just periodically, a new character doesn't show up in the list of characters. I can't trace the pattern.

So far, I haven't had problems with characters not showing in the list. For the rest, everything is happening as you said.
