### ISSUE TITLE
Infinite Loop?

### ISSUE THREAD

**Issue by highjohnconquer** [TavernAI/TavernAI-v1#129]
Exception occurred during processing of request from ('127.0.0.1', 56831)
Traceback (most recent call last):
  File "E:\Documents\AI\one-click-installers-oobabooga-windows\installer_files\env\lib\socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "E:\Documents\AI\one-click-installers-oobabooga-windows\installer_files\env\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "E:\Documents\AI\one-click-installers-oobabooga-windows\installer_files\env\lib\socketserver.py", line 747, in __init__
    self.handle()
  File "E:\Documents\AI\one-click-installers-oobabooga-windows\installer_files\env\lib\http\server.py", line 433, in handle
    self.handle_one_request()
  File "E:\Documents\AI\one-click-installers-oobabooga-windows\installer_files\env\lib\http\server.py", line 421, in handle_one_request
    method()
  File "E:\Documents\AI\one-click-installers-oobabooga-windows\text-generation-webui\extensions\api\script.py", line 40, in do_POST
    while len(prompt_lines) >= 0 and len(encode('\n'.join(prompt_lines))) > max_context:
  File "E:\Documents\AI\one-click-installers-oobabooga-windows\text-generation-webui\modules\text_generation.py", line 31, in encode
    input_ids = shared.tokenizer.encode(str(prompt), return_tensors='pt', add_special_tokens=add_special_tokens)
AttributeError: 'NoneType' object has no attribute 'encode'

...127.0.0.1 - - [14/Apr/2023 04:13:03] "GET /api/v1/model HTTP/1.1" 200 -
127.0.0.1 - - [14/Apr/2023 04:13:06] "GET /api/v1/model HTTP/1.1" 200 -
127.0.0.1 - - [14/Apr/2023 04:13:09] "GET /api/v1/model HTTP/1.1" 200 -
127.0.0.1 - - [14/Apr/2023 04:13:12] "GET /api/v1/model HTTP/1.1" 200 -
127.0.0.1 - - [14/Apr/2023 04:13:15] "GET /api/v1/model HTTP/1.1" 200 -...

(infinite)

![image](https://user-images.githubusercontent.com/46117736/232003174-87ec3f6e-b557-4572-a47c-055287c6f056.png)

**Comment by Gahless** [comment]
same for me

**Comment by Olama12345** [comment]
Got the exact same error

**Comment by walbuuk** [comment]
I have the same constant output of " "GET /api/v1/model HTTP/1.1" 200 -" in the console with both koboltcpp and oobabooga api and AI not responding, but apparently TavernAI doesn't like firefox. I switched to chrome and now the AI is responding, while cmd is outputting the same message.

**Comment by Death-777** [comment]
I'm getting the same problem, haven't found a fix yet. I'm using a 30b Alpaca model with oobabooga.

**Comment by fuzzah** [comment]
The infinite calls are fine, it's just the way TavernAI talks to KoboldAPI. The real problem is the AttributeError exception above the repeating messages.

Try this: in TavernAI settings click "Connect". If instead of "not connected" it says "None", then you are successfully connected to the API, but currently no model is loaded on the KoboldAPI server (web ui). This can happen if you start web ui without specifying `--model` and then forget to select a model in settings. In this case try selecting/reloading your model on the Model tab in text generation web ui.

If a model name is displayed in TavernAI (like on the above screenshot), then make sure the model is properly loaded: again, go to web ui and reload the model. No errors should be displayed in web ui and in its terminal output.

Hope this helps

**Comment by grobique** [comment]
Im having kind of this problem while running on colab, and resource monitor shows full VRAM usage. I bet lack of 16 gigs of VRAM is the culprit
