### ISSUE TITLE
Invalid csrf token

### ISSUE THREAD

**Issue by Recentiv** [TavernAI/TavernAI-v1#185]
I searched your discord and found other people having the same problem I face with no solutions. So I thought I should open an issue.

The Problem I Face when trying to use Tavern AI is that I need to reconnect very often, as it gives me this Error Every Three Generations or so. Sometimes even a Restart is needed, and sometimes it just doesn't connect outright until i reboot my PC. The Same Happens With Silly tavern just so you know.

Here is the Error Code it gives me:

ForbiddenError: invalid csrf token
    at doubleCsrf (C:\snapshot\TavernAI\node_modules\csrf-csrf\lib\cjs\index.cjs:18:61)
    at Object.<anonymous> (C:\snapshot\TavernAI\server.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:651:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:591:12)
    at Function.Module._load (internal/modules/cjs/loader.js:583:3)
    at Function.runMain (pkg/prelude/bootstrap.js:1983:12)
    at startup (internal/bootstrap/node.js:320:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:660:3)

**Comment by Borov666** [comment]
At the moment, you can disable csrf token in config.conf set this:

const csrf_token = false;

But this may partially reduce security. There is no need to restart the computer here, if you get this error, it is enough to restart TavernAI in the browser by closing the other tabs with TavernAI .

**Comment by Recentiv** [comment]
Sadly, it didn't fix the problem, but now it doesn't give me an error I could give to help further diagnose it.
