### ISSUE TITLE
PayloadTooLargeError - Conversations stop being saved past a certain point.

### ISSUE THREAD

**Issue by Xiphus** [TavernAI/TavernAI-v1#23]
When your conversation goes on for a long time. Eventually you start getting an error in the command prompt and your chatlog no longer saves any further messages.

Here's the full error message:

PayloadTooLargeError: request entity too large
    at readStream (C:\TavernAI--1.2.5\node_modules\raw-body\index.js:156:17)
    at getRawBody (C:\node_modules\raw-body\index.js:109:12)
    at read (C:\TavernAI--1.2.5\node_modules\body-parser\lib\read.js:79:3)
    at jsonParser (C:\TavernAI--1.2.5\node_modules\body-parser\lib\types\json.js:135:5)
    at Layer.handle [as handle_request] (C:\TavernAI--1.2.5\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\TavernAI--1.2.5\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\TavernAI--1.2.5\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\TavernAI--1.2.5\node_modules\express\lib\router\layer.js:95:5)
    at C:\TavernAI--1.2.5\ode_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\TavernAI--1.2.5\node_modules\express\lib\router\index.js:346:12)
    
The only way to fix this currently is to go and manually delete parts of the chatlog to shorten the conversation so it can continue saving them.

**Comment by Borov666** [comment]
What is the chat file size?

**Comment by Xiphus** [comment]
100KB

**Comment by Neutrovertido** [comment]
I can confirm this issue... conversations won't save for some reason. My chat file size is 672KB

**Comment by Neutrovertido** [comment]
I opened up a PR at #24 that addresses this issue, hopefully maintainer can review it soon

**Comment by Borov666** [comment]
Temporary solution, I leave the topic open.

**Comment by Kippykip** [comment]
![image_2023-01-31_214302602](https://user-images.githubusercontent.com/33023808/215750866-b01a7289-44e2-4a84-a67e-c7e19197ab5e.png)
Same here at about 100kb, gonna try updating now
EDIT: Updating fixed it
